/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.ItemController;

/**
 *
 * @author Gustavo
 */
public class TelaCadastroItem extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroItem
     */
    
    private ItemController control;
    public Integer id;
    
    public TelaCadastroItem() {
        initComponents();
        id=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lAno = new javax.swing.JPanel();
        lAutor1 = new javax.swing.JLabel();
        txtAutor1 = new javax.swing.JTextField();
        lAutor2 = new javax.swing.JLabel();
        txtAutor2 = new javax.swing.JTextField();
        lTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lEditora = new javax.swing.JLabel();
        txtEditora = new javax.swing.JTextField();
        lAssunto = new javax.swing.JLabel();
        txtAssunto = new javax.swing.JTextField();
        lPalavraChave1 = new javax.swing.JLabel();
        txtPalavrachave1 = new javax.swing.JTextField();
        txtPalavrachave2 = new javax.swing.JTextField();
        lPalavraChave2 = new javax.swing.JLabel();
        lCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lCdu = new javax.swing.JLabel();
        ftfCdu = new javax.swing.JFormattedTextField();
        lTipo = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        lCategoria = new javax.swing.JLabel();
        rbCategoria = new javax.swing.JComboBox<>();
        lISBN = new javax.swing.JLabel();
        ftfISBN = new javax.swing.JFormattedTextField();
        lPagina = new javax.swing.JLabel();
        ftfPagina = new javax.swing.JFormattedTextField();
        cbxEmprestado = new javax.swing.JCheckBox();
        lEdicao = new javax.swing.JLabel();
        txtEdicao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tItem = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEmprestimo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de item");

        lAno.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do item"));

        lAutor1.setText("Autor 1:");

        txtAutor1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAutor1FocusGained(evt);
            }
        });

        lAutor2.setText("Autor 2:");

        txtAutor2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAutor2FocusGained(evt);
            }
        });

        lTitulo.setText("Titulo:");

        txtTitulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTituloFocusGained(evt);
            }
        });

        lEditora.setText("Editora:");

        txtEditora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEditoraFocusGained(evt);
            }
        });

        lAssunto.setText("Assunto:");

        txtAssunto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAssuntoFocusGained(evt);
            }
        });

        lPalavraChave1.setText("Palavra chave 1:");

        txtPalavrachave1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPalavrachave1FocusGained(evt);
            }
        });

        txtPalavrachave2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPalavrachave2FocusGained(evt);
            }
        });

        lPalavraChave2.setText("Palavra chave 2:");

        lCidade.setText("Cidade:");

        txtCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCidadeFocusGained(evt);
            }
        });

        lCdu.setText("CDU:");

        try {
            ftfCdu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.##:###.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCdu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftfCduFocusGained(evt);
            }
        });

        lTipo.setText("Tipo:");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Livro", "Periódico", "TCC", "Relatório", "Mídia", "Cartaz", "Mapa" }));
        cbTipo.setToolTipText("");
        cbTipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbTipoFocusGained(evt);
            }
        });
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        lCategoria.setText("Categoria:");

        rbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Revista", "Jornal" }));
        rbCategoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rbCategoriaFocusGained(evt);
            }
        });

        lISBN.setText("ISBN:");

        try {
            ftfISBN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-####-###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfISBN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftfISBNFocusGained(evt);
            }
        });

        lPagina.setText("Página:");

        try {
            ftfPagina.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("### pag.: ### cm")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfPagina.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftfPaginaFocusGained(evt);
            }
        });

        cbxEmprestado.setText("Emprestado");
        cbxEmprestado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbxEmprestadoFocusGained(evt);
            }
        });

        lEdicao.setText("Edição:");

        txtEdicao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEdicaoFocusGained(evt);
            }
        });

        jLabel1.setText("Ano:");

        txtAno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAnoFocusGained(evt);
            }
        });

        javax.swing.GroupLayout lAnoLayout = new javax.swing.GroupLayout(lAno);
        lAno.setLayout(lAnoLayout);
        lAnoLayout.setHorizontalGroup(
            lAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lAnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(lAnoLayout.createSequentialGroup()
                            .addGroup(lAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(lAnoLayout.createSequentialGroup()
                                    .addComponent(lAutor1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAutor1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(lAnoLayout.createSequentialGroup()
                                    .addComponent(lAutor2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAutor2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(lAnoLayout.createSequentialGroup()
                                    .addComponent(lTitulo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(lAnoLayout.createSequentialGroup()
                                    .addComponent(lEditora)
                                    .addGap(12, 12, 12)
                                    .addComponent(txtEditora)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(lAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(lAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(lAnoLayout.createSequentialGroup()
                                        .addComponent(lCdu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ftfCdu))
                                    .addGroup(lAnoLayout.createSequentialGroup()
                                        .addComponent(lISBN)
                                        .addGap(18, 18, 18)
                                        .addComponent(ftfISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(lAnoLayout.createSequentialGroup()
                                    .addComponent(lPagina)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ftfPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cbxEmprestado)))
                        .addGroup(lAnoLayout.createSequentialGroup()
                            .addGroup(lAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(lAnoLayout.createSequentialGroup()
                                    .addComponent(lAssunto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAssunto))
                                .addGroup(lAnoLayout.createSequentialGroup()
                                    .addComponent(lPalavraChave1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPalavrachave1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
                                .addGroup(lAnoLayout.createSequentialGroup()
                                    .addComponent(lPalavraChave2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPalavrachave2)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(lAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(lAnoLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtAno))
                                .addGroup(lAnoLayout.createSequentialGroup()
                                    .addComponent(lEdicao)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtEdicao)))))
                    .addGroup(lAnoLayout.createSequentialGroup()
                        .addComponent(lTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(lCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lAnoLayout.createSequentialGroup()
                        .addComponent(lCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        lAnoLayout.setVerticalGroup(
            lAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lAnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lCdu)
                        .addComponent(ftfCdu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lAutor1)
                        .addComponent(txtAutor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAutor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAutor2)
                    .addComponent(lISBN)
                    .addComponent(ftfISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTitulo)
                    .addComponent(lPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEditora)
                    .addComponent(cbxEmprestado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAssunto)
                    .addComponent(lEdicao)
                    .addComponent(txtEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPalavrachave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPalavraChave1)
                    .addComponent(jLabel1)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPalavrachave2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPalavraChave2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCidade)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTipo)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCategoria)
                    .addComponent(rbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulo", "Editora", "CDU"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tItem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tItemFocusGained(evt);
            }
        });
        tItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tItem);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEmprestimo.setText("Emprestimo");
        btnEmprestimo.setEnabled(false);
        btnEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEmprestimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lAno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir)
                    .addComponent(btnEmprestimo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbTipoFocusGained
        // TODO add your handling code here:
        control.limparSelecaoTabela();
    }//GEN-LAST:event_cbTipoFocusGained

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        // TODO add your handling code here:
        control.setCategoriaByTipo();
    }//GEN-LAST:event_cbTipoActionPerformed

    private void rbCategoriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbCategoriaFocusGained
        // TODO add your handling code here:
        control.limparSelecaoTabela();
    }//GEN-LAST:event_rbCategoriaFocusGained

    private void txtAutor1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAutor1FocusGained
        // TODO add your handling code here:
        control.limparSelecaoTabela();
    }//GEN-LAST:event_txtAutor1FocusGained

    private void txtAutor2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAutor2FocusGained
        // TODO add your handling code here:
        control.limparSelecaoTabela();
    }//GEN-LAST:event_txtAutor2FocusGained

    private void txtTituloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTituloFocusGained
        // TODO add your handling code here:
        control.limparSelecaoTabela();
    }//GEN-LAST:event_txtTituloFocusGained

    private void txtEditoraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEditoraFocusGained
        // TODO add your handling code here:
        control.limparSelecaoTabela();
    }//GEN-LAST:event_txtEditoraFocusGained

    private void txtAssuntoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAssuntoFocusGained
        // TODO add your handling code here:
        control.limparSelecaoTabela();
    }//GEN-LAST:event_txtAssuntoFocusGained

    private void txtPalavrachave1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPalavrachave1FocusGained
        // TODO add your handling code here:
        control.limparSelecaoTabela();
    }//GEN-LAST:event_txtPalavrachave1FocusGained

    private void txtPalavrachave2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPalavrachave2FocusGained
        // TODO add your handling code here:
        control.limparSelecaoTabela();
    }//GEN-LAST:event_txtPalavrachave2FocusGained

    private void txtCidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCidadeFocusGained
        // TODO add your handling code here:
        control.limparSelecaoTabela();
    }//GEN-LAST:event_txtCidadeFocusGained

    private void ftfCduFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftfCduFocusGained
        // TODO add your handling code here:
        control.limparSelecaoTabela();
    }//GEN-LAST:event_ftfCduFocusGained

    private void ftfISBNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftfISBNFocusGained
        // TODO add your handling code here:
        control.limparSelecaoTabela();
    }//GEN-LAST:event_ftfISBNFocusGained

    private void ftfPaginaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftfPaginaFocusGained
        // TODO add your handling code here:
        control.limparSelecaoTabela();
    }//GEN-LAST:event_ftfPaginaFocusGained

    private void cbxEmprestadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxEmprestadoFocusGained
        // TODO add your handling code here:
        control.limparSelecaoTabela();
    }//GEN-LAST:event_cbxEmprestadoFocusGained

    private void tItemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tItemFocusGained
        // TODO add your handling code here:
        if (gettItem().getSelectedRow() >= 0) {
            getBtnExcluir().setEnabled(true);
            getBtnEmprestimo().setEnabled(true);
        }
    }//GEN-LAST:event_tItemFocusGained

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        control.inserirItem(id);
        id++;
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        control.excluirDados();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestimoActionPerformed
        // TODO add your handling code here:
        control.realizarEmprestimo();
    }//GEN-LAST:event_btnEmprestimoActionPerformed

    private void txtEdicaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEdicaoFocusGained
        // TODO add your handling code here:
        control.limparSelecaoTabela();
    }//GEN-LAST:event_txtEdicaoFocusGained

    private void txtAnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnoFocusGained
        // TODO add your handling code here:
        control.limparSelecaoTabela();
    }//GEN-LAST:event_txtAnoFocusGained

    private void tItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tItemMouseClicked
        // TODO add your handling code here:
        if (gettItem().getSelectedRow() >= 0) {
            getBtnExcluir().setEnabled(true);
            getBtnEmprestimo().setEnabled(true);
        }
    }//GEN-LAST:event_tItemMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmprestimo;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JCheckBox cbxEmprestado;
    private javax.swing.JFormattedTextField ftfCdu;
    private javax.swing.JFormattedTextField ftfISBN;
    private javax.swing.JFormattedTextField ftfPagina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel lAno;
    private javax.swing.JLabel lAssunto;
    private javax.swing.JLabel lAutor1;
    private javax.swing.JLabel lAutor2;
    private javax.swing.JLabel lCategoria;
    private javax.swing.JLabel lCdu;
    private javax.swing.JLabel lCidade;
    private javax.swing.JLabel lEdicao;
    private javax.swing.JLabel lEditora;
    private javax.swing.JLabel lISBN;
    private javax.swing.JLabel lPagina;
    private javax.swing.JLabel lPalavraChave1;
    private javax.swing.JLabel lPalavraChave2;
    private javax.swing.JLabel lTipo;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JComboBox<String> rbCategoria;
    private javax.swing.JTable tItem;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtAssunto;
    private javax.swing.JTextField txtAutor1;
    private javax.swing.JTextField txtAutor2;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEdicao;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtPalavrachave1;
    private javax.swing.JTextField txtPalavrachave2;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the control
     */
    public ItemController getControl() {
        return control;
    }

    /**
     * @param control the control to set
     */
    public void setControl(ItemController control) {
        this.control = control;
    }

    /**
     * @return the btnEmprestimo
     */
    public javax.swing.JButton getBtnEmprestimo() {
        return btnEmprestimo;
    }

    /**
     * @param btnEmprestimo the btnEmprestimo to set
     */
    public void setBtnEmprestimo(javax.swing.JButton btnEmprestimo) {
        this.btnEmprestimo = btnEmprestimo;
    }

    /**
     * @return the btnExcluir
     */
    public javax.swing.JButton getBtnExcluir() {
        return btnExcluir;
    }

    /**
     * @param btnExcluir the btnExcluir to set
     */
    public void setBtnExcluir(javax.swing.JButton btnExcluir) {
        this.btnExcluir = btnExcluir;
    }

    /**
     * @return the btnSalvar
     */
    public javax.swing.JButton getBtnSalvar() {
        return btnSalvar;
    }

    /**
     * @param btnSalvar the btnSalvar to set
     */
    public void setBtnSalvar(javax.swing.JButton btnSalvar) {
        this.btnSalvar = btnSalvar;
    }

    /**
     * @return the cbTipo
     */
    public javax.swing.JComboBox<String> getCbTipo() {
        return cbTipo;
    }

    /**
     * @param cbTipo the cbTipo to set
     */
    public void setCbTipo(javax.swing.JComboBox<String> cbTipo) {
        this.cbTipo = cbTipo;
    }

    /**
     * @return the cbxEmprestado
     */
    public javax.swing.JCheckBox getCbxEmprestado() {
        return cbxEmprestado;
    }

    /**
     * @param cbxEmprestado the cbxEmprestado to set
     */
    public void setCbxEmprestado(javax.swing.JCheckBox cbxEmprestado) {
        this.cbxEmprestado = cbxEmprestado;
    }

    /**
     * @return the ftfISBN
     */
    public javax.swing.JFormattedTextField getFtfISBN() {
        return ftfISBN;
    }

    /**
     * @param ftfISBN the ftfISBN to set
     */
    public void setFtfISBN(javax.swing.JFormattedTextField ftfISBN) {
        this.ftfISBN = ftfISBN;
    }

    /**
     * @return the ftfPagina
     */
    public javax.swing.JFormattedTextField getFtfPagina() {
        return ftfPagina;
    }

    /**
     * @param ftfPagina the ftfPagina to set
     */
    public void setFtfPagina(javax.swing.JFormattedTextField ftfPagina) {
        this.ftfPagina = ftfPagina;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return getlAno();
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.setlAno(jPanel1);
    }

    /**
     * @return the jPanel2
     */
    public javax.swing.JPanel getjPanel2() {
        return jPanel2;
    }

    /**
     * @param jPanel2 the jPanel2 to set
     */
    public void setjPanel2(javax.swing.JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the lAssunto
     */
    public javax.swing.JLabel getlAssunto() {
        return lAssunto;
    }

    /**
     * @param lAssunto the lAssunto to set
     */
    public void setlAssunto(javax.swing.JLabel lAssunto) {
        this.lAssunto = lAssunto;
    }

    /**
     * @return the lAutor1
     */
    public javax.swing.JLabel getlAutor1() {
        return lAutor1;
    }

    /**
     * @param lAutor1 the lAutor1 to set
     */
    public void setlAutor1(javax.swing.JLabel lAutor1) {
        this.lAutor1 = lAutor1;
    }

    /**
     * @return the lAutor2
     */
    public javax.swing.JLabel getlAutor2() {
        return lAutor2;
    }

    /**
     * @param lAutor2 the lAutor2 to set
     */
    public void setlAutor2(javax.swing.JLabel lAutor2) {
        this.lAutor2 = lAutor2;
    }

    /**
     * @return the lCategoria
     */
    public javax.swing.JLabel getlCategoria() {
        return lCategoria;
    }

    /**
     * @param lCategoria the lCategoria to set
     */
    public void setlCategoria(javax.swing.JLabel lCategoria) {
        this.lCategoria = lCategoria;
    }

    /**
     * @return the lCdu
     */
    public javax.swing.JLabel getlCdu() {
        return lCdu;
    }

    /**
     * @param lCdu the lCdu to set
     */
    public void setlCdu(javax.swing.JLabel lCdu) {
        this.lCdu = lCdu;
    }

    /**
     * @return the lCidade
     */
    public javax.swing.JLabel getlCidade() {
        return lCidade;
    }

    /**
     * @param lCidade the lCidade to set
     */
    public void setlCidade(javax.swing.JLabel lCidade) {
        this.lCidade = lCidade;
    }

    /**
     * @return the lEditora
     */
    public javax.swing.JLabel getlEditora() {
        return lEditora;
    }

    /**
     * @param lEditora the lEditora to set
     */
    public void setlEditora(javax.swing.JLabel lEditora) {
        this.lEditora = lEditora;
    }

    /**
     * @return the lISBN
     */
    public javax.swing.JLabel getlISBN() {
        return lISBN;
    }

    /**
     * @param lISBN the lISBN to set
     */
    public void setlISBN(javax.swing.JLabel lISBN) {
        this.lISBN = lISBN;
    }

    /**
     * @return the lPagina
     */
    public javax.swing.JLabel getlPagina() {
        return lPagina;
    }

    /**
     * @param lPagina the lPagina to set
     */
    public void setlPagina(javax.swing.JLabel lPagina) {
        this.lPagina = lPagina;
    }

    /**
     * @return the lPalavraChave1
     */
    public javax.swing.JLabel getlPalavraChave1() {
        return lPalavraChave1;
    }

    /**
     * @param lPalavraChave1 the lPalavraChave1 to set
     */
    public void setlPalavraChave1(javax.swing.JLabel lPalavraChave1) {
        this.lPalavraChave1 = lPalavraChave1;
    }

    /**
     * @return the lPalavraChave2
     */
    public javax.swing.JLabel getlPalavraChave2() {
        return lPalavraChave2;
    }

    /**
     * @param lPalavraChave2 the lPalavraChave2 to set
     */
    public void setlPalavraChave2(javax.swing.JLabel lPalavraChave2) {
        this.lPalavraChave2 = lPalavraChave2;
    }

    /**
     * @return the lTipo
     */
    public javax.swing.JLabel getlTipo() {
        return lTipo;
    }

    /**
     * @param lTipo the lTipo to set
     */
    public void setlTipo(javax.swing.JLabel lTipo) {
        this.lTipo = lTipo;
    }

    /**
     * @return the lTitulo
     */
    public javax.swing.JLabel getlTitulo() {
        return lTitulo;
    }

    /**
     * @param lTitulo the lTitulo to set
     */
    public void setlTitulo(javax.swing.JLabel lTitulo) {
        this.lTitulo = lTitulo;
    }

    /**
     * @return the rbCategoria
     */
    public javax.swing.JComboBox<String> getCbCategoria() {
        return rbCategoria;
    }

    /**
     * @param rbCategoria the rbCategoria to set
     */
    public void setCbCategoria(javax.swing.JComboBox<String> rbCategoria) {
        this.rbCategoria = rbCategoria;
    }

    /**
     * @return the tItem
     */
    public javax.swing.JTable gettItem() {
        return tItem;
    }

    /**
     * @param tItem the tItem to set
     */
    public void settItem(javax.swing.JTable tItem) {
        this.tItem = tItem;
    }

    /**
     * @return the tftCdu
     */
    public javax.swing.JFormattedTextField getFtfCdu() {
        return ftfCdu;
    }

    /**
     * @param tftCdu the tftCdu to set
     */
    public void setFtfCdu(javax.swing.JFormattedTextField tftCdu) {
        this.ftfCdu = tftCdu;
    }

    /**
     * @return the txtAssunto
     */
    public javax.swing.JTextField getTxtAssunto() {
        return txtAssunto;
    }

    /**
     * @param txtAssunto the txtAssunto to set
     */
    public void setTxtAssunto(javax.swing.JTextField txtAssunto) {
        this.txtAssunto = txtAssunto;
    }

    /**
     * @return the txtAutor1
     */
    public javax.swing.JTextField getTxtAutor1() {
        return txtAutor1;
    }

    /**
     * @param txtAutor1 the txtAutor1 to set
     */
    public void setTxtAutor1(javax.swing.JTextField txtAutor1) {
        this.txtAutor1 = txtAutor1;
    }

    /**
     * @return the txtAutor2
     */
    public javax.swing.JTextField getTxtAutor2() {
        return txtAutor2;
    }

    /**
     * @param txtAutor2 the txtAutor2 to set
     */
    public void setTxtAutor2(javax.swing.JTextField txtAutor2) {
        this.txtAutor2 = txtAutor2;
    }

    /**
     * @return the txtCidade
     */
    public javax.swing.JTextField getTxtCidade() {
        return txtCidade;
    }

    /**
     * @param txtCidade the txtCidade to set
     */
    public void setTxtCidade(javax.swing.JTextField txtCidade) {
        this.txtCidade = txtCidade;
    }

    /**
     * @return the txtEditora
     */
    public javax.swing.JTextField getTxtEditora() {
        return txtEditora;
    }

    /**
     * @param txtEditora the txtEditora to set
     */
    public void setTxtEditora(javax.swing.JTextField txtEditora) {
        this.txtEditora = txtEditora;
    }

    /**
     * @return the txtPalavrachave1
     */
    public javax.swing.JTextField getTxtPalavrachave1() {
        return txtPalavrachave1;
    }

    /**
     * @param txtPalavrachave1 the txtPalavrachave1 to set
     */
    public void setTxtPalavrachave1(javax.swing.JTextField txtPalavrachave1) {
        this.txtPalavrachave1 = txtPalavrachave1;
    }

    /**
     * @return the txtPalavrachave2
     */
    public javax.swing.JTextField getTxtPalavrachave2() {
        return txtPalavrachave2;
    }

    /**
     * @param txtPalavrachave2 the txtPalavrachave2 to set
     */
    public void setTxtPalavrachave2(javax.swing.JTextField txtPalavrachave2) {
        this.txtPalavrachave2 = txtPalavrachave2;
    }

    /**
     * @return the txtTitulo
     */
    public javax.swing.JTextField getTxtTitulo() {
        return txtTitulo;
    }

    /**
     * @param txtTitulo the txtTitulo to set
     */
    public void setTxtTitulo(javax.swing.JTextField txtTitulo) {
        this.txtTitulo = txtTitulo;
    }

    /**
     * @return the lEdicao
     */
    public javax.swing.JLabel getlEdicao() {
        return lEdicao;
    }

    /**
     * @param lEdicao the lEdicao to set
     */
    public void setlEdicao(javax.swing.JLabel lEdicao) {
        this.lEdicao = lEdicao;
    }

    /**
     * @return the txtEdicao
     */
    public javax.swing.JTextField getTxtEdicao() {
        return txtEdicao;
    }

    /**
     * @return the lAno
     */
    public javax.swing.JPanel getlAno() {
        return lAno;
    }

    /**
     * @param lAno the lAno to set
     */
    public void setlAno(javax.swing.JPanel lAno) {
        this.lAno = lAno;
    }

    /**
     * @return the txtAno
     */
    public javax.swing.JTextField getTxtAno() {
        return txtAno;
    }

    /**
     * @param txtAno the txtAno to set
     */
    public void setTxtAno(javax.swing.JTextField txtAno) {
        this.txtAno = txtAno;
    }
}
