/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.FichaController;
import control.ItemController;
import control.ListaController;
import control.LoginController;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Acervo;

/**
 *
 * @author Gustavo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private ArrayList<Acervo> listAcervo;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        listAcervo = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mLogin = new javax.swing.JMenu();
        miLogar = new javax.swing.JMenuItem();
        mAcervo = new javax.swing.JMenu();
        miCaddastrar = new javax.swing.JMenuItem();
        miItens = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Poor Richard", 1, 78)); // NOI18N
        jLabel1.setText("Acervo");

        mLogin.setText("Login");

        miLogar.setText("Logar");
        miLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogarActionPerformed(evt);
            }
        });
        mLogin.add(miLogar);

        jMenuBar1.add(mLogin);

        mAcervo.setText("Acervo");

        miCaddastrar.setText("Cadastrar item");
        miCaddastrar.setToolTipText("");
        miCaddastrar.setEnabled(false);
        miCaddastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCaddastrarActionPerformed(evt);
            }
        });
        mAcervo.add(miCaddastrar);

        miItens.setText("Itens");
        miItens.setEnabled(false);
        miItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miItensActionPerformed(evt);
            }
        });
        mAcervo.add(miItens);

        jMenuBar1.add(mAcervo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogarActionPerformed
        // TODO add your handling code here:
        TelaLogin tl = new TelaLogin(this, false);
        LoginController control = new LoginController(tl, this);
        tl.setControl(control);
        tl.setVisible(true);
    }//GEN-LAST:event_miLogarActionPerformed

    private void miCaddastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCaddastrarActionPerformed
        // TODO add your handling code here:
        TelaCadastroItem tci = new TelaCadastroItem();
        ItemController control;

        try {
            control = new ItemController(tci, listAcervo);
            tci.setControl(control);
            tci.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao acessar o banco de dados!", "Erro no banco de dados", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_miCaddastrarActionPerformed

    private void miItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miItensActionPerformed
        // TODO add your handling code here:
        TelaItens ti = new TelaItens(listAcervo);
        ListaController control = new ListaController(ti, listAcervo);
        ti.setControl(control);
        ti.setVisible(true);
    }//GEN-LAST:event_miItensActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mAcervo;
    private javax.swing.JMenu mLogin;
    private javax.swing.JMenuItem miCaddastrar;
    private javax.swing.JMenuItem miItens;
    private javax.swing.JMenuItem miLogar;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * @return the jMenuBar1
     */
    public javax.swing.JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    /**
     * @param jMenuBar1 the jMenuBar1 to set
     */
    public void setjMenuBar1(javax.swing.JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    /**
     * @return the mAcervo
     */
    public javax.swing.JMenu getmAcervo() {
        return mAcervo;
    }

    /**
     * @param mAcervo the mAcervo to set
     */
    public void setmAcervo(javax.swing.JMenu mAcervo) {
        this.mAcervo = mAcervo;
    }

    /**
     * @return the mLogin
     */
    public javax.swing.JMenu getmLogin() {
        return mLogin;
    }

    /**
     * @param mLogin the mLogin to set
     */
    public void setmLogin(javax.swing.JMenu mLogin) {
        this.mLogin = mLogin;
    }

    /**
     * @return the miCaddastrar
     */
    public javax.swing.JMenuItem getMiCaddastrar() {
        return miCaddastrar;
    }

    /**
     * @param miCaddastrar the miCaddastrar to set
     */
    public void setMiCaddastrar(javax.swing.JMenuItem miCaddastrar) {
        this.miCaddastrar = miCaddastrar;
    }

    /**
     * @return the miItens
     */
    public javax.swing.JMenuItem getMiItens() {
        return miItens;
    }

    /**
     * @param miItens the miItens to set
     */
    public void setMiItens(javax.swing.JMenuItem miItens) {
        this.miItens = miItens;
    }

    /**
     * @return the miLogar
     */
    public javax.swing.JMenuItem getMiLogar() {
        return miLogar;
    }

    /**
     * @param miLogar the miLogar to set
     */
    public void setMiLogar(javax.swing.JMenuItem miLogar) {
        this.miLogar = miLogar;
    }
}
