/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.FichaController;
import control.ListaController;
import java.util.ArrayList;
import model.Acervo;

/**
 *
 * @author Gustavo
 */
public class TelaItens extends javax.swing.JFrame {
    
    private ListaController control;
    private ArrayList<Acervo> listAcervo;

    /**
     * Creates new form TelaItens
     */
    public TelaItens(ArrayList<Acervo> listAcervo) {
        initComponents();
        this.listAcervo=listAcervo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tItens = new javax.swing.JTable();
        btnFicha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulo", "Editora", "CDU"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tItens.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tItensFocusGained(evt);
            }
        });
        tItens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tItensMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tItens);

        btnFicha.setText("Ficha Catalográfica");
        btnFicha.setEnabled(false);
        btnFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFichaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFicha)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFicha)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tItensFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tItensFocusGained
        // TODO add your handling code here:
        if(gettItens().getSelectedRow()>=0){
            getBtnFicha().setEnabled(true);
        }
    }//GEN-LAST:event_tItensFocusGained

    private void btnFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFichaActionPerformed
        // TODO add your handling code here:
        Acervo acervo = control.retornarAcervoTabela();
        
        TelaFicha tf = new TelaFicha();
        FichaController control2 = new FichaController(tf, acervo, listAcervo);
        tf.setControl(control2);
        tf.setVisible(true);
        
    }//GEN-LAST:event_btnFichaActionPerformed

    private void tItensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tItensMouseClicked
        // TODO add your handling code here:
        if(gettItens().getSelectedRow()>=0){
            getBtnFicha().setEnabled(true);
        }
    }//GEN-LAST:event_tItensMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFicha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tItens;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the control
     */
    public ListaController getControl() {
        return control;
    }

    /**
     * @param control the control to set
     */
    public void setControl(ListaController control) {
        this.control = control;
    }

    /**
     * @return the btnFicha
     */
    public javax.swing.JButton getBtnFicha() {
        return btnFicha;
    }

    /**
     * @param btnFicha the btnFicha to set
     */
    public void setBtnFicha(javax.swing.JButton btnFicha) {
        this.btnFicha = btnFicha;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the tItens
     */
    public javax.swing.JTable gettItens() {
        return tItens;
    }

    /**
     * @param tItens the tItens to set
     */
    public void settItens(javax.swing.JTable tItens) {
        this.tItens = tItens;
    }

    /**
     * @return the listAcervo
     */
    public ArrayList<Acervo> getListAcervo() {
        return listAcervo;
    }

    /**
     * @param listAcervo the listAcervo to set
     */
    public void setListAcervo(ArrayList<Acervo> listAcervo) {
        this.listAcervo = listAcervo;
    }
}
